name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            zip \
            unzip \
            openjdk-11-jdk \
            git \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --force-reinstall cython==0.29.19
        pip install buildozer

    - name: Verify Cython installation
      run: |
        cython --version
        python -c "import cython; print(f'Cython version: {cython.__version__}')"

    - name: Build APK
      run: |
        buildozer init
        sed -i "s/^requirements = .*/requirements = python3==3.8,kivy==2.1.0,kivymd==0.104.2,openssl,sqlite3,pillow/" buildozer.spec
        buildozer -v android debug
        mkdir -p dist
        cp bin/*.apk dist/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: dist/*.apk
        retention-days: 5
