name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # 3. Install system dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            git autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libtinfo5 \
            cmake libffi-dev libssl-dev python3-dev

    # 4. Install Python packages
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" "buildozer>=1.4.0"
        pip cache purge

    # 5. Create buildozer.spec
    - name: Create configuration
      run: |
        cat > buildozer.spec <<EOL
        [app]
        title = MyApp
        package.name = myapp
        package.domain = org.mydomain
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf,json
        version = 0.1
        requirements = python3==3.8,kivy==2.1.0,kivymd==1.1.1,openssl,sqlite3,pillow
        android.ndk = 23b
        android.sdk = 33
        android.api = 33
        android.minapi = 21
        android.arch = arm64-v8a
        presplash.filename = %(source.dir)s/assets/icon.png
        icon.filename = %(source.dir)s/assets/icon.png
        EOL

    # 6. Build the APK
    - name: Build Android package
      run: |
        buildozer android clean
        buildozer -v android debug 2>&1 | tee build.log
        mkdir -p dist
        find bin -name '*.apk' -exec cp {} dist/ \;

    # 7. Upload artifacts (UPDATED TO v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: dist/*.apk
        if-no-files-found: error

    # 8. Upload logs if failed
    - name: Upload build logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build.log
