name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            git autoconf libtool pkg-config \
            zlib1g-dev libncurses-dev \
            libtinfo6 cmake libffi-dev \
            libssl-dev python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" "buildozer>=1.5.0" "python-for-android==2024.1.21"
        pip cache purge

    - name: Initialize Buildozer
      run: |
        buildozer init
        buildozer android update

    - name: Configure buildozer.spec
      run: |
        cat > buildozer.spec <<EOL
        [app]
        title = MyApp
        package.name = myapp
        package.domain = org.mydomain
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf,json
        version = 0.1
        requirements = python3==3.8,kivy==2.1.0,kivymd==1.1.1,openssl,sqlite3,pillow
        android.archs = arm64-v8a
        android.ndk_version = 25b
        android.min_sdk_version = 21
        android.target_sdk_version = 33
        presplash.filename = %(source.dir)s/assets/icon.png
        icon.filename = %(source.dir)s/assets/icon.png
        EOL

    - name: Build APK
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        mkdir -p dist
        find bin -name '*.apk' -exec cp {} dist/ \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: dist/*.apk
        if-no-files-found: error
        retention-days: 7
