name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            git autoconf libtool pkg-config \
            zlib1g-dev libncurses-dev \
            libtinfo6 cmake libffi-dev \
            libssl-dev python3-dev

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.2.9519653'
        cmake-version: '3.22.1'
        build-tools-version: '34.0.0'

    - name: Accept all licenses and install packages
      run: |
        mkdir -p "$ANDROID_HOME/licenses"
        echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        
        yes | sdkmanager --licenses
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-33"
        sdkmanager --list_installed

    - name: Verify Android tools
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME/build-tools/34.0.0
        $ANDROID_HOME/build-tools/34.0.0/aidl --version
        echo "PATH: $PATH"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --no-cache-dir "cython<3.0" "buildozer>=1.5.0" "python-for-android==2024.1.21"
        pip cache purge

    - name: Initialize Buildozer environment
      run: |
        buildozer init || true
        # Get the actual python-for-android installation path
        P4A_PATH=$(python -c "import os, pythonforandroid; print(os.path.dirname(pythonforandroid.__file__))")
        # Create the directory structure Buildozer expects
        mkdir -p ~/.buildozer/android/platform
        # Copy the entire python-for-android package to where Buildozer expects it
        cp -r $P4A_PATH ~/.buildozer/android/platform/python-for-android

    - name: Configure buildozer.spec
      run: |
        cat > buildozer.spec <<EOL
        [app]
        title = MyApp
        package.name = myapp
        package.domain = org.mydomain
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf,json
        version = 0.1
        requirements = python3==3.10,kivy==2.2.1,kivymd==1.2.0,openssl,sqlite3,pillow
        android.archs = arm64-v8a
        android.ndk_path = $ANDROID_HOME/ndk/25.2.9519653
        android.sdk_dir = $ANDROID_HOME
        android.build_tools_dir = $ANDROID_HOME/build-tools/34.0.0
        android.min_sdk_version = 21
        android.target_sdk_version = 33
        presplash.filename = %(source.dir)s/assets/icon.png
        icon.filename = %(source.dir)s/assets/icon.png
        EOL

    - name: Build APK
      run: |
        export PATH=$ANDROID_HOME/build-tools/34.0.0:$PATH
        buildozer android clean
        buildozer -v android debug 2>&1 | tee build.log
        mkdir -p dist
        find bin -name '*.apk' -exec cp {} dist/ \;
        if [ ! -f dist/*.apk ]; then
          echo "APK build failed!"
          cat build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: dist/*.apk
        if-no-files-found: error
        retention-days: 7

    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: build.log
        retention-days: 7
