name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - run: pip install buildozer
    - run: buildozer init
    - run: buildozer -v android debug
    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
